import fs from "node:fs/promises";
import path from "node:path";
import { runCliCaptured } from "../support/cli.js";
import { tempDir } from "../support/temp.js";

const SPEC = {
  openapi: "3.1.0",
  info: { title: "members", version: "1.0.0" },
  paths: {
    "/api/members": {
      get: {
        responses: {
          "200": {
            description: "ok",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: { id: { type: "string" }, email: { type: "string" } },
                    required: ["id", "email"],
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

describe("generate CLI", () => {
  it("emits schema.d.ts only — the artifact dir is openapi.json + schema.d.ts (RV-020)", async () => {
    const tempDirectory = await tempDir("rivet-ts-generate-");
    const generatedRoot = path.join(tempDirectory, "generated");

    await fs.mkdir(generatedRoot, { recursive: true });
    await fs.writeFile(
      path.join(generatedRoot, "openapi.json"),
      `${JSON.stringify(SPEC, null, 2)}\n`,
    );
    // A pre-facade scaffold may have left index.ts inside generated/; the
    // facade lives in src/ now, so generate must clean the stale copy up.
    await fs.writeFile(path.join(generatedRoot, "index.ts"), "// stale facade\n");

    expect((await runCliCaptured(["generate", "--generated-root", generatedRoot])).exitCode).toBe(
      0,
    );

    const schemaSource = await fs.readFile(path.join(generatedRoot, "schema.d.ts"), "utf8");
    expect(schemaSource).toContain("auto-generated by openapi-typescript");
    expect(schemaSource).toContain("export interface paths");
    expect(schemaSource).toContain('"/api/members"');
    expect(schemaSource).toContain("email: string;");

    const entries = await fs.readdir(generatedRoot);
    expect(entries.sort()).toEqual(["openapi.json", "schema.d.ts"]);
  });

  it("is idempotent: re-running over unchanged inputs rewrites nothing", async () => {
    const tempDirectory = await tempDir("rivet-ts-generate-idem-");
    const generatedRoot = path.join(tempDirectory, "generated");

    await fs.mkdir(generatedRoot, { recursive: true });
    await fs.writeFile(
      path.join(generatedRoot, "openapi.json"),
      `${JSON.stringify(SPEC, null, 2)}\n`,
    );

    expect((await runCliCaptured(["generate", "--generated-root", generatedRoot])).exitCode).toBe(
      0,
    );
    const firstSchemaStat = await fs.stat(path.join(generatedRoot, "schema.d.ts"));

    expect((await runCliCaptured(["generate", "--generated-root", generatedRoot])).exitCode).toBe(
      0,
    );
    const secondSchemaStat = await fs.stat(path.join(generatedRoot, "schema.d.ts"));

    expect(secondSchemaStat.mtimeMs).toBe(firstSchemaStat.mtimeMs);
  });

  it("fails loudly when openapi.json is missing", async () => {
    const tempDirectory = await tempDir("rivet-ts-generate-missing-");
    const generatedRoot = path.join(tempDirectory, "generated");
    await fs.mkdir(generatedRoot, { recursive: true });

    const { exitCode, stderr } = await runCliCaptured([
      "generate",
      "--generated-root",
      generatedRoot,
    ]);
    expect(exitCode).toBe(1);

    expect(stderr).toContain("OpenAPI spec not found");
    expect(stderr).toContain("--output");
  });

  it("returns usage error when --generated-root is omitted", async () => {
    const { exitCode, stderr } = await runCliCaptured(["generate"]);
    expect(exitCode).toBe(1);

    expect(stderr).toContain("rivet-ts generate --generated-root <dir>");
  });
});
