import fs from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";

/**
 * The hand-written client facade over the generated artifacts. Emitted ONCE at
 * scaffold time into the contracts package's `src/` — never into `generated/`.
 * The artifact dir stays `openapi.json` + `schema.d.ts` only (Meridian
 * RV-020 v2: generated dirs are read-only and contain nothing hand-shaped);
 * the facade is static (it doesn't depend on the contract), so it is
 * user-owned after the first emit.
 */
export const emitClientFacadeSource = (): string =>
  [
    "// Hand-written facade over the generated OpenAPI artifacts — the only",
    "// non-generated file in this package. `generated/` stays read-only:",
    "// `openapi.json` comes from the Rivet binary, `schema.d.ts` from",
    "// openapi-typescript (both via `task generate`).",
    'import createOpenApiClient, { type Client, type ClientOptions } from "openapi-fetch";',
    'import type { paths } from "../generated/schema.js";',
    "",
    'export type { components, paths } from "../generated/schema.js";',
    "",
    "export type RivetFetch = (input: Request) => Promise<Response>;",
    "",
    'export type RivetConfig = Omit<ClientOptions, "baseUrl" | "fetch"> & {',
    "  readonly baseUrl?: string;",
    "  readonly fetch?: RivetFetch;",
    "};",
    "",
    "export type RivetClient = Client<paths>;",
    "",
    "export const createClient = (config: RivetConfig = {}): RivetClient =>",
    "  createOpenApiClient<paths>(config);",
    "",
    "export let client: RivetClient = createOpenApiClient<paths>();",
    "",
    "export const configureRivet = (config: RivetConfig): void => {",
    "  client = createClient(config);",
    "};",
    "",
  ].join("\n");

const readOpenApiSpec = async (openApiPath: string): Promise<OpenAPI3> => {
  let raw: string;
  try {
    raw = await fs.readFile(openApiPath, "utf8");
  } catch {
    throw new Error(
      `Cannot generate the client package: OpenAPI spec not found at ${openApiPath}. ` +
        "Run the Rivet binary first (rivet --from <contract.json> --output <dir> writes <dir>/openapi.json).",
    );
  }

  return JSON.parse(raw) as OpenAPI3;
};

const SCHEMA_HEADER = [
  "/**",
  " * This file was auto-generated by openapi-typescript.",
  " * Do not make direct changes to the file.",
  " */",
  "",
  "",
].join("\n");

export const emitClientSchemaSource = async (openApiPath: string): Promise<string> => {
  const ast = await openapiTS(await readOpenApiSpec(openApiPath));
  return `${SCHEMA_HEADER}${astToString(ast)}`;
};

const writeIfChanged = async (outputPath: string, source: string): Promise<void> => {
  try {
    const current = await fs.readFile(outputPath, "utf8");
    if (current === source) {
      return;
    }
  } catch {
    // noop
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, source, "utf8");
};

/**
 * Emits `schema.d.ts` (openapi-typescript over `<generatedRoot>/openapi.json`)
 * into the generated artifact dir. Types only — the artifact dir holds exactly
 * `openapi.json` + `schema.d.ts` (RV-020 v2); the client facade lives in the
 * contracts package's `src/` and is emitted once at scaffold time.
 */
export const emitClientPackage = async (
  generatedRoot: string,
  openApiPath: string = path.join(generatedRoot, "openapi.json"),
): Promise<void> => {
  const schemaSource = await emitClientSchemaSource(openApiPath);
  await writeIfChanged(path.join(generatedRoot, "schema.d.ts"), schemaSource);
  // A pre-facade scaffold may have left index.ts inside generated/; it now
  // lives in src/, so a stale copy here is a doctrine violation. Remove it.
  await fs.rm(path.join(generatedRoot, "index.ts"), { force: true });
};
