import fs from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString, type OpenAPI3 } from "openapi-typescript";

/**
 * The generated client package wraps `openapi-fetch` over the OpenAPI spec
 * emitted by the Rivet binary. Its surface is deliberately minimal:
 *
 * - `paths` types from `schema.d.ts` (produced by `openapi-typescript`),
 * - `createClient` returning a typed `openapi-fetch` client,
 * - a `configureRivet`/`client` pair preserving the "configure once" seam the
 *   local-first story relies on (`rivet-ts/local` swaps in a custom `fetch`
 *   that dispatches to `app.request`).
 */
export const emitClientPackageSource = (): string =>
  [
    "/* Generated by rivet-ts. Do not edit. */",
    'import createOpenApiClient, { type Client, type ClientOptions } from "openapi-fetch";',
    'import type { paths } from "./schema.js";',
    "",
    'export type { paths } from "./schema.js";',
    "",
    "export type RivetFetch = (input: Request) => Promise<Response>;",
    "",
    'export type RivetConfig = Omit<ClientOptions, "baseUrl" | "fetch"> & {',
    "  readonly baseUrl: string;",
    "  readonly fetch?: RivetFetch;",
    "};",
    "",
    "export type RivetClient = Client<paths>;",
    "",
    "export const createClient = (config: RivetConfig): RivetClient =>",
    "  createOpenApiClient<paths>(config);",
    "",
    "export let client: RivetClient = createOpenApiClient<paths>();",
    "",
    "export const configureRivet = (config: RivetConfig): void => {",
    "  client = createClient(config);",
    "};",
    "",
  ].join("\n");

const readOpenApiSpec = async (openApiPath: string): Promise<OpenAPI3> => {
  let raw: string;
  try {
    raw = await fs.readFile(openApiPath, "utf8");
  } catch {
    throw new Error(
      `Cannot generate the client package: OpenAPI spec not found at ${openApiPath}. ` +
        "Run the Rivet binary with --openapi first.",
    );
  }

  return JSON.parse(raw) as OpenAPI3;
};

export const emitClientSchemaSource = async (openApiPath: string): Promise<string> => {
  const ast = await openapiTS(await readOpenApiSpec(openApiPath));
  return astToString(ast);
};

const writeIfChanged = async (outputPath: string, source: string): Promise<void> => {
  try {
    const current = await fs.readFile(outputPath, "utf8");
    if (current === source) {
      return;
    }
  } catch {
    // noop
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, source, "utf8");
};

/**
 * Emits `schema.d.ts` (openapi-typescript over `<generatedRoot>/openapi.json`)
 * and the `index.ts` client facade into the generated client root.
 */
export const emitClientPackage = async (
  generatedRoot: string,
  openApiPath: string = path.join(generatedRoot, "openapi.json"),
): Promise<void> => {
  const schemaSource = await emitClientSchemaSource(openApiPath);
  await writeIfChanged(path.join(generatedRoot, "schema.d.ts"), schemaSource);
  await writeIfChanged(path.join(generatedRoot, "index.ts"), emitClientPackageSource());
};
